name: Push Nuget Packages to Nuget.Org

on:
  workflow_run:
    workflows: [".NET Core"]
    branches: [ master ]
    types:
      - completed
jobs:
  publish:
    name: publish nuget packages
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        
      # Publish ARConsistency
      - name: publish on version change ARConsistency
        id: publish_nuget_arconsistency
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: ARConsistency/ARConsistency.csproj
          PACKAGE_NAME: ARConsistency
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          
      # Publish ARConsistency.Abstractions
      - name: publish on version change ARConsistency.Abstractions
        id: publish_nuget_abstractions
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: ARConsistency.Abstractions/ARConsistency.Abstractions.csproj
          PACKAGE_NAME: ARConsistency.Abstractions
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
